#!/usr/bin/env bash

if [ $# == 0 ]; then
    exit 3
fi

APP_DIR=`pwd`
if [[ -d "$APP_DIR/app" && -f "$APP_DIR/app/.bash_cli" ]]; then
    APP_DIR="$APP_DIR/app"
fi

if [[ ! -f "$APP_DIR/.bash_cli" ]]; then
    >&2 echo -e "\e[31mYou are not within a Bash CLI project\e[39m"
    >&2 echo "Please change your directory to a valid project or run the init command to set one up."
    exit 1
fi

CMD_DIR="$APP_DIR"

if [[ $# -gt 1 ]]; then
    for i in $(($#-1)); do
        DIR=${!i}
        CMD_DIR="$CMD_DIR/$DIR"
        if [[ ! -d "$CMD_DIR" ]]; then
            exit 0
        fi
    done
fi

CMD_NAME="${!#}"
if [[ -f "$CMD_DIR/$CMD_NAME" ]]; then
    rm -f "$CMD_DIR/$CMD_NAME"
    rm -f "$CMD_DIR/$CMD_NAME.help"
    rm -f "$CMD_DIR/$CMD_NAME.usage"
elif [[ -d "$CMD_DIR/$CMD_NAME" ]]; then
    rm -Rf "$CMD_DIR/$CMD_NAME"
else
    echo -e "\e[31mCommand \e[36m$@\e[31m did not exist\e[39m"
    exit 1
fi

echo -e "\e[32mCommand \e[36m$@\e[32m successfully removed\e[39m"
