#!/usr/bin/env bash


function _bash_cli() {
    local root_dir;
    root_dir=$(dirname "$(realpath "$(which "${COMP_WORDS[0]}")")")
    
    # shellcheck source=./bash-cli.inc.sh
    . "$root_dir/bash-cli.inc.sh"

    bcli_bash_completions
}
