#!/usr/bin/env bash

if [ $# == 0 ]; then
    exit 3
fi

APP_DIR=`pwd`

if [[ -f "$APP_DIR/.bash_cli" ]]; then
    APP_DIR=`dirname "$APP_DIR"`
fi

if [[ ! -f "$APP_DIR/app/.bash_cli" ]]; then
    >&2 echo -e "\033[31mYou are not within a Bash CLI project\033[39m"
    >&2 echo "Please change your directory to a valid project or run the init command to set one up."
    exit 1
fi

NAME="$1"
FOLDER="${2-"/usr/bin"}"
BASH_COMPLETION="/etc/bash_completion.d/"

if [ "$(uname)" == "Darwin" ]; then
    if [ -d "$(brew --prefix)/etc/bash_completion.d" ]; then
        BASH_COMPLETION="$(brew --prefix)$BASH_COMPLETION"
    fi
    if [ "$FOLDER" == "/usr/bin" ]; then
      FOLDER="/usr/local/bin"
    fi
fi

ln -snf "$APP_DIR/cli" "$FOLDER/$NAME"

cat > "$BASH_COMPLETION/$NAME" <<EOC
source "$APP_DIR/complete"
complete -F _bash_cli $NAME
EOC
